# Generated by Django 2.1.5 on 2020-02-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_auto_20200211_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bios',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
