# Generated by Django 2.1.5 on 2020-02-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_auto_20200211_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bios',
            name='phone_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
